version: "3.8"
services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./expense-tracker-backend
    ports:
      - "5000:5000"
    env_file:
      - ./expense-tracker-backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./expense-tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
